name: 'UI Tests'

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  ui-tests:
    strategy:
      fail-fast: false
      matrix:
        test: [ DetailsTabUiTest, FreeStyleConfigurationUiTest, GlobalConfigurationUiTest, IssuesColumnUiTest, SnippetGeneratorUiTest, TrendChartsUiTest, WarningsPluginUiTest, SmokeTests ]
        browser: [ firefox-container, chrome-container ]

    runs-on: [ubuntu-latest]
    name: '${{ matrix.browser }} / ${{ matrix.test }}'

    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
        if: github.event_name == 'pull_request_target'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Build warnings plugin and download dependencies
        run: mvn -V --color always -ntp verify -Pskip --file plugin/pom.xml
      - name: Run UI tests ${{ matrix.test }} on ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
          SKIP_UPDATES: 'true'
        run: mvn -V --color always -ntp test --file ui-tests/pom.xml -Dtest=${{ matrix.test }} -Dquite -Dgpg.skip -Dsurefire.rerunFailingTestsCount=1
